// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg_8KNFkm4EnhPPvLecNuNYWh8pdD8d5I',
    appId: '1:350031470992:web:4e61e9ec1f979c07129315',
    messagingSenderId: '350031470992',
    projectId: 'practice-firebase-a6ad4',
    authDomain: 'practice-firebase-a6ad4.firebaseapp.com',
    storageBucket: 'practice-firebase-a6ad4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIi0GqfPAAMobupeaPefURb949F8jvToc',
    appId: '1:350031470992:android:e5a1cc1e7af689b8129315',
    messagingSenderId: '350031470992',
    projectId: 'practice-firebase-a6ad4',
    storageBucket: 'practice-firebase-a6ad4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADxw8g0fx8WSXoZQXj7TQWCeFX6J_os7A',
    appId: '1:350031470992:ios:ad22b5cd56adccec129315',
    messagingSenderId: '350031470992',
    projectId: 'practice-firebase-a6ad4',
    storageBucket: 'practice-firebase-a6ad4.firebasestorage.app',
    iosBundleId: 'com.example.practiceFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADxw8g0fx8WSXoZQXj7TQWCeFX6J_os7A',
    appId: '1:350031470992:ios:ad22b5cd56adccec129315',
    messagingSenderId: '350031470992',
    projectId: 'practice-firebase-a6ad4',
    storageBucket: 'practice-firebase-a6ad4.firebasestorage.app',
    iosBundleId: 'com.example.practiceFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg_8KNFkm4EnhPPvLecNuNYWh8pdD8d5I',
    appId: '1:350031470992:web:80858979f1b6d9f7129315',
    messagingSenderId: '350031470992',
    projectId: 'practice-firebase-a6ad4',
    authDomain: 'practice-firebase-a6ad4.firebaseapp.com',
    storageBucket: 'practice-firebase-a6ad4.firebasestorage.app',
  );
}
